#!/bin/bash

apt-get update
apt-get upgrade
apt-get install apache2 -y
apt-get install unzip -y

echo "Baixando e copiando arquivos da aplicação no GIThub"

cd /tmp

wget https://github.com/denilsonbonatti/linux-site-dio/archive/refs/heads/main.zip
unzip main.zip
cd linux-site-dio-main

echo "Copiando para o diretório do Apache"
cp -R * /var/www/html/
